A. Умножение матриц 2024

Напишите функцию, реализующую матричное умножение. Для этого реализуйте функцию

In [4]:
import numpy as np
import typing as tp

import scipy.stats as sps

In [26]:
def matrix_multiplication(A: np.ndarray, B: np.ndarray) -> np.ndarray:    
    return np.sum(A[:, :, np.newaxis] * B.reshape(1, B.shape[0], B.shape[1]), axis=1)

In [27]:
A = np.linspace(1, 2, 25).reshape(5, 5)
B = np.linspace(2, 3, 25).reshape(5, 5)
C = matrix_multiplication(A, B)


B. Ближайшие соседи 2024

In [38]:
import numpy as np
import typing as tp

def find_nearest_points(A: np.ndarray, B: np.ndarray, k: int):
    A = A[np.newaxis, :]
    B = B[:, np.newaxis]
    metrics = np.sqrt(np.sum((A - B) ** 2, axis=2))
    return metrics.argsort(axis=1)[:, :k] + 1, metrics

In [42]:
A = np.random.uniform(0, 10, size=(5, 2))
B = np.random.uniform(0, 10, size=(5, 2))
res, metr = find_nearest_points(A, B, 3)
print(A)
print()
print(B)
print()
res, metr

[[5.29827504 3.59020648]
 [7.9001699  1.94711603]
 [0.16775688 8.10449687]
 [0.39187982 7.57357899]
 [3.29296861 4.87669258]]

[[1.22975322 1.88924382]
 [4.84103542 1.25756845]
 [3.1653799  6.59557466]
 [4.60085359 9.2433826 ]
 [3.59990374 5.75217384]]



(array([[5, 1, 4],
        [1, 2, 5],
        [5, 4, 3],
        [4, 5, 3],
        [5, 1, 4]]),
 array([[4.4097782 , 6.67066772, 6.30533161, 5.74575479, 3.63066218],
        [2.3770293 , 3.13588578, 8.28975037, 7.72573457, 3.93631431],
        [3.6853059 , 6.63523956, 3.35597825, 2.9408834 , 1.72361089],
        [5.69603344, 8.00755856, 4.57705223, 4.52810162, 4.55834892],
        [2.74928498, 5.74201654, 4.16089602, 3.6890289 , 0.92772658]]))

In [45]:
A = np.array([[0, 0], [1, 0], [2, 0]])
B = np.array([[0, 1], [2, 1]])
res, metr = find_nearest_points(A, B, 2)
res, metr

(array([[1, 2],
        [3, 2]]),
 array([[1.        , 1.41421356, 2.23606798],
        [2.23606798, 1.41421356, 1.        ]]))